name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          cd react-app-2
          npm ci
      - name: Lint code
        run: |
          cd react-app-2
          npm run lint
      - name: Test code
        run: |
          cd react-app-2
          npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          cd react-app-2
          npm ci
      - name: Build website
        run: |
          cd react-app-2
          npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-app-2-build
          path: react-app-2/build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
