name: my-first-action
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My first action step
        run: echo "Hello, world!"
      - name: Checking date and time
        run: date
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Checking runner OS
        run: |
          echo "The runner OS is $RUNNER_OS"
          echo "The runner name is $RUNNER_NAME"
          echo "The runner temp directory is $RUNNER_TEMP"
          echo "The runner workspace is $RUNNER_WORKSPACE"