name: my-first-action
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My first action step
        run: echo "Hello, world!"
      - name: Checking date and time
        run: date
      - name: Print goodbye
        run: echo "Done - bye!"
    