name: react-app-tests
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd react-app
          npm install
      - name: Run tests
        run: |
          cd react-app
          npm test
      - name: Print Test completion
        run: echo "Tests Completed with no errors!"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd react-app
          npm install
      - name: Build the app
        run: |
          cd react-app
          npm run build
      - name: Deploy the app
        run: echo "Deploying the app..."
      